"""add full schema

Revision ID: 241e61dd1924
Revises: 3a73fc4b41d1
Create Date: 2025-09-21 23:44:32.870332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241e61dd1924'
down_revision: Union[str, Sequence[str], None] = '3a73fc4b41d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('auth_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('top_tracks_7d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='uq_user_track_7d')
    )
    op.create_index(op.f('ix_plays_played_at'), 'plays', ['played_at'], unique=False)
    op.add_column('tracks', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('tracks', sa.Column('album_id', sa.Integer(), nullable=False))
    op.add_column('tracks', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.add_column('tracks', sa.Column('provider_track_id', sa.String(), nullable=False))
    op.create_unique_constraint('uq_provider_track', 'tracks', ['provider_id', 'provider_track_id'])
    op.create_foreign_key(None, 'tracks', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'tracks', 'providers', ['provider_id'], ['id'])
    op.create_foreign_key(None, 'tracks', 'albums', ['album_id'], ['id'])
    op.drop_column('tracks', 'artist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint('uq_provider_track', 'tracks', type_='unique')
    op.drop_column('tracks', 'provider_track_id')
    op.drop_column('tracks', 'provider_id')
    op.drop_column('tracks', 'album_id')
    op.drop_column('tracks', 'artist_id')
    op.drop_index(op.f('ix_plays_played_at'), table_name='plays')
    op.drop_table('top_tracks_7d')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    op.drop_table('albums')
    op.drop_table('providers')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
